///////This class is used creates the account based on the lead status //////

public Class CreatingAccount {
 //method implementation here
   ///changes aug17 //////////////

 
    public Account createAccount(String name) { //method to create account
        Account acc = new Account();
        acc.Name = name;
        return acc;
        ///////method end here with implementation////// 
             ///changes aug17 //////////////
             
             ///changes September 8th //////////////
            ///Test ////////////// 

        
    }
}